### ISSUE TITLE
Change table name in `registered-students` route

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/library-management-system#13]
"All Students Registered" tab shows incorrect table name
It should be more user understandable like "All students approved to access Library facilities"

**Comment by pbarnum** [comment]
I can update this. Is "All students approved to access Library facilities" what you want? "All students approved" might get the point across while keeping it short. But I'm here to help not dictate.

**Comment by prabhakar267** [comment]
Latter one sounds better :+1:

**Comment by prabhakar267** [comment]
Closed in #21
