### ISSUE TITLE
Change table name in `all-books` route

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/library-management-system#14]
"All Books in Library" tab shows incorrect table name
It should be more user understandable like "Books available in Library to be accessed by Students"

**Comment by geekfred** [comment]
"Books accesible by Students" should be understandable enough?
or "Avaliable Books accesible by Students"
or "All Books accesible by Students"

**Comment by prabhakar267** [comment]
@geekfred Yes, it was changed to "Books available to Students"

Fixed in #20

**Comment by geekfred** [comment]
Ah! Much better!
