### ISSUE TITLE
Add nbproject folder to gitignore

### ISSUE THREAD

**Issue by deepu9** [prabhakar267/library-management-system#33]
Hi,
Can you add nbproject folder to gitignore. As you already know that's a IDE specific config and should never be pushed to repos. Thanks

**Comment by prabhakar267** [comment]
@deepu9 thanks for pointing out, never realised it that i missed it in .gitignore.
Can you raise a PR for the same? 
Thanks

**Comment by deepu9** [comment]
Sure

**Comment by prabhakar267** [comment]
#34
