### ISSUE TITLE
update to laravel 5.6?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [prabhakar267/library-management-system#39]
just checking if are there interesting in this update...

**Comment by prabhakar267** [comment]
Not sure about the benefits of migrating from 4.7 to 5.6
But if there is any thing we can gain, then yes, I will be more than happy about the migration 👍

**Comment by thiagogomesverissimo** [comment]
@prabhakar267,

I think the idea is to be more in consonance with PHP new features (and remove deprecated things)...
I spent some time today to up your project in ubuntu 18.04 and php 7.2 because mcrypt :wolf: 

However, I never used lavarel before 5 version, but I can try to update it.

**Comment by prabhakar267** [comment]
Great
Go ahead, let me know if you need some help 😄

**Comment by thiagogomesverissimo** [comment]
Just to let you know, I am working in this upgrade:

https://github.com/thiagogomesverissimo/library-management-system/tree/upgrade-to-5.8

**Comment by barkermn01** [comment]
I know this issue is defunct now as Laravel has been updated to 6.20 in commit fda8903c8a30e5634ac804b5175e9f9f42e3a46e but does this mean the dependency on mcrypt has been removed, as when I search the source code I only see mcrypt used in the config? @prabhakar267
