### ISSUE TITLE
Add instructions to install MySQL in Linux

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/library-management-system#40]
Currently there are only [instructions](https://github.com/prabhakar267/library-management-system/blob/master/README.md#unix--linux--mac-setup) to setup PHP and the project but no setup instructions for MySQL in Linux/Unix.
Add instructions in [README.md](https://github.com/prabhakar267/library-management-system/blob/master/README.md)

**Comment by scottswezey** [comment]
The MySQL docs already provide detailed instructions for various methods to install MySQL. Would a minor update to the readme, which offers basic guidance and links to the relevant mysql docs be sufficient? If so, I can create a PR for your review.

---

While most of the instructions in the mysql docs can be copied into to the readme, I see a few potential issues:

1. Instructions are slightly different depending on the package manager.
2. Installation from source is much more complex and will require other dependencies.
3. The size of the readme will be unnecessarily large to include multiple sets of similar directions to setup mysql. This takes the focus off of the project and risks confusing any non-technical users.
4. The correct instructions may change over time, meaning that the documentation offered in the readme could become outdated.

**Comment by prabhakar267** [comment]
> Would a minor update to the readme, which offers basic guidance and links to the relevant mysql docs be sufficient
@scottswezey Yes
