### ISSUE TITLE
encryption mismatch

### ISSUE THREAD

**Issue by CharlesKumar** [prabhakar267/library-management-system#5]
I got a problem with encryption method

It says "Function mcrypt_get_iv_size() is deprecated "

how to solve this issue
![probl](https://user-images.githubusercontent.com/14817903/27816333-8db32e8a-60a8-11e7-88bd-b133ec8e6ea8.png)

Can i use this in laravel 5.4

**Comment by CharlesKumar** [comment]
should i have to upgrade from 4.2.x to 5.x

**Comment by prabhakar267** [comment]
Hi @CharlesKumar 
I built library-management-system using Laravel 4.2 (https://laravel.com/docs/4.2/introduction) that's why some of the features of that version have depreciated in the newer versions.

I am not sure how to upgrade the version of Laravel, maybe you could follow some blog and upgrade the project accordingly. I will also search for some relevant tools and blog posts which can help us in the upgradation.

**Comment by CharlesKumar** [comment]
I think the easier way to do is to install laravel 5.0 and then copy composer dependencies, .env, unique files from this "prabhakar267/library-management-system" repository.to the new installation.

The new directory structure may be adopted or update classmap directive in composer.json, User Autentication Model and Blade templates changed a bit.

we may repeat if we need to update from 5.0 to latest

I will try my best thanks for your quick response.

**Comment by prabhakar267** [comment]
I think we might be able to find something simple to port 4.2 to 5.0 because a lot of projects would have done that. 
Before building a new 5.0 project, I think porting would be a better and cleaner option. (Just an opinion, open for discussion 😄

**Comment by CharlesKumar** [comment]
may be porting works like a charm 

For now these two choices:

1. paid option using [laravel shift](https://laravelshift.com/upgrade-laravel-4.2-to-laravel-5.0)
2. Manual [upgrade guide](https://mattstauffer.co/blog/upgrading-from-laravel-4-to-laravel-5)

**Comment by CharlesKumar** [comment]
add the following to the beginning of config/app.php

`error_reporting(E_ALL ^ E_DEPRECATED);`

solved the issue by referring [this stackoverflow thread](https://stackoverflow.com/questions/42515368/function-mcrypt-get-iv-size-is-deprecated-on-laravel-4)

**Comment by prabhakar267** [comment]
@CharlesKumar ```error_reporting(E_ALL ^ E_DEPRECATED);``` only avoids showing error, it doesn't solve the problem.
Maybe some updated version of the same function could help us?

**Comment by pbarnum** [comment]
I also received this error. The reason why this happened (at least for me) is because of the version of PHP I was using (7.1) Downgrading to 5.6 and making sure php5.6-mcrypt is installed will fix the issue. This should probably be noted in the README for installing the project.

**Comment by prabhakar267** [comment]
Fixed in  #24
