### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Patchwork\Utf8\Bootup

### ISSUE THREAD

**Issue by basamoahjnr** [prabhakar267/library-management-system#61]
i get this error message on composer install

PHP Fatal error:  Uncaught Error: Class 'Patchwork\Utf8\Bootup' not found in /opt/bitnami/apache/htdocs/bootstrap/autoload.php:46
Stack trace:
#0 /opt/bitnami/apache/htdocs/artisan(16): require()
#1 {main}
  thrown in /opt/bitnami/apache/htdocs/bootstrap/autoload.php on line 46
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255

**Comment by Emmanuel-Odero** [comment]
To fix that I ran the command:
`composer require patchwork/utf8`

**Comment by basamoahjnr** [comment]
> To fix that I ran the command: `composer require patchwork/utf8`

this worked, but i can see you posted an issue after of which i am getting same error
