### ISSUE TITLE
 Hello developers, can you add a version number?

### ISSUE THREAD

**Issue by 0clickjacking0** [prabhakar267/library-management-system#63]

**Comment by sagnik26** [comment]
Hey, Can I work on this issue

**Comment by prabhakar267** [comment]
@0clickjacking0 Can you add more details?

**Comment by 0clickjacking0** [comment]
> @0clickjacking0 Can you add more details?

just add a version to tags

**Comment by prabhakar267** [comment]
Sure. Will take care in future. Thanks @0clickjacking0
